baseURL = "https://labbots.github.io/bash-utility/"
languageCode = "en-us"
title = "Bash Utility"
theme = "hugo-theme-learn"
canonifyurls = true
googleAnalytics= "UA-75820294-2"
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  disableNextPrev = true
  showVisitedLinks = false
[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Bash Utility"
identifier = "bash-utility-repo"
url = "https://github.com/labbots/bash-utility"
weight = 1
[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Bash Oneliner"
identifier = "bash-oneliner-repo"
url = "https://github.com/labbots/bash-oneliners"
weight = 9
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
